import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import BigPost from '../components/bigPost';
import Layout from '../components/layout';
import List from '../components/list';
import ListItem from '../components/listItem';
import Sidebar from '../components/sidebar';

const Home: NextPage = () => {
  return (
    <Layout home bigPost={<BigPost />}>
      <Head>
        <title>Astral Codex Ten</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col">
        <div className="grid lg:grid-cols-4 gap-8">
          <main className="col-span-3">
            <List />
          </main>
          <aside className="col-span-1">
            <Sidebar />
          </aside>
        </div>
      </div>
    </Layout>
  );
};

export default Home;
