import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import BigPost from '../components/bigPost';
import Layout from '../components/layout';
import List from '../components/list';
import ListItem from '../components/listItem';
import Sidebar from '../components/sidebar';
import { AllPostsData } from '../interfaces';
import { getSortedPostsData } from '../lib/posts';

export const getStaticProps: GetStaticProps = async () => {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
};

const Home = ({ allPostsData }: { allPostsData: AllPostsData[] }) => {
  console.log(typeof allPostsData);
  const renderPosts = () => {
    return allPostsData.map((post) => <div key={post.id}>{post.title}</div>);
  };
  return (
    <Layout home bigPost={<BigPost />}>
      <Head>
        <title>Astral Codex Ten</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full">
        <div className="grid grid-cols-1 w-full sm:grid-cols-4 gap-8">
          <main className="col-span-3">
            <List allPostsData={allPostsData} />
          </main>
          <aside className="col-span-1">
            <Sidebar />
          </aside>
        </div>
      </div>
    </Layout>
  );
};

export default Home;
